### ISSUE TITLE
ReferenceError: fetch is not defined

### ISSUE THREAD

**Issue by codelife123** [br4adam/ticket-management#1]
I'm getting following error in server when I try to login using google auth

ReferenceError: fetch is not defined
    at /home/user/Desktop/temp/ticket-management/server/dist/api/google.js:26:26
    at Generator.next (<anonymous>)
    at /home/user/Desktop/temp/ticket-management/server/dist/api/google.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/user/Desktop/temp/ticket-management/server/dist/api/google.js:4:12)
    at getIdToken (/home/user/Desktop/temp/ticket-management/server/dist/api/google.js:24:30)
    at /home/user/Desktop/temp/ticket-management/server/dist/routes/login.js:36:48
    at Generator.next (<anonymous>)
    at /home/user/Desktop/temp/ticket-management/server/dist/routes/login.js:8:71
    at new Promise (<anonymous>)

Node JS - v14.17.6

**Comment by codelife123** [comment]
it was my mistake.
 this version of node is not supporting fetch
